spring.application.name=Test_Assessment_Project

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-calm-paper-a1vzntf9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HfAN0eUh3EBs

server.port=8789
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud-name=djacwdcvq
cloudinary.api-key=556553641571212
cloudinary.api-secret=RZPYFPrmJYn6yXl8ZYfJUeY7bnI

#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

